const backgrounds = {
  "Ravager": 0,
  "Slums": 1,
  "Glitch District": 2,
  "Mid Town": 3,
  "Shibuya": 4,
  "Byte Street": 5,
  "Aries Compound": 6,
  "Highland Core": 7,
  "Citadel Park": 8,
  "Citadel Tower": 9,
  "Omnipresent": 10,
  "Citadel Penthouse": 11,
}
const maleHelmets = {
  "VR Visor": 0,
  "Motocross Helmet": 1,
  "Gas Mask": 2,
  "Typical Cyber Helm 1": 3,
  "Typical Cyber Helm 2": 4,
  "Typical Cyber Helm 3": 5,
  "Business Helmet 1": 6,
  "Business Helmet 2": 7,
  "Business Helmet 3": 8,
  "Trash Helmet": 9,
  "Robot Head": 10,
  "Cyber Football 1": 11,
  "Cyber Football 2": 12,
  "Blitz Ball Fan Helmet 1": 13,
  "Blitz Ball Fan Helmet 2": 14,
  "Rave Helmet 1": 15,
  "Rave Helmet 2": 16,
  "Middle Class Helm 1": 17,
  "Middle Class Helm 2": 18,
  "Construction Helmet": 19,
  "VIP Robot Head": 20,
  "Blitz Ball Player": 21,
  "Shark Helm": 22,
  "Medieval": 23,
  "Soldier 1": 24,
  "Soldier 2": 25,
  "Pilot Helm": 26,
  "Beer Hat helm": 27,
  "DJ Helm": 28,
  "Ghost Robot": 29,
  "Samurai Mask": 30,
  "Fire Helm": 31,
  "Ice Helm": 32,
  "Electric Helm": 33,
  "Water Helm": 34,
  "Ape Helm": 35,
  "Zombie Robot": 36,
  "Luxury Robot": 37,
  "Dwemer Robot": 38,
  "Skull": 39,
  "Gold Skull": 40,
  "Gold Robot": 41,
  "Diamond Multi Color Samurai": 42,
  "Demon": 43,
  "Laser Eyes": 44,
  "Giant Mech": 45,
  "Bored Ape": 46,
  "Crypto Punk": 47,
  "Devil 1": 43,
  "Devil 2": 43,
  "Devil 3": 43,
  "Angel 1": 42,
  "Angel 2": 48, // missing, but maps to this currently
  "Angel 3": 49, // missing, but maps to this currently
  "Dark Space Wizard": 50,
  "Tri-Angle Hero": [51, '51-0'],
  "Chief Master": 52,
  "Doom Man": 53,
  "Ichigo": 54,
  "Metraidish": 55,
  "Super Italian Guy": 56,
}
const maleClothing = {
  "Work Clothes 1": 0,
  "Work Clothes 2": 1,
  "Work Clothes 3": 2,
  "Bar Outfit 1": 3,
  "Bar Outfit 2": 4,
  "Bar Outfit 3": 5,
  "Scavenger 1": 6,
  "Scavenger 2": 7,
  "Scavenger 3": 8,
  "Grunt 1": 9,
  "Grunt 2": 10,
  "Tee Shirt 1": 11,
  "Tee Shirt 2": 12,
  "Tee Shirt 3": 13,
  "Suit 1": 14,
  "Suit 2": 15,
  "Suit 3": 16,
  "Hoodie 1": 17,
  "Hoodie 2": 18,
  "Hoodie 3": 19,
  "Rave": 20,
  "Kimono": 21,
  "No Shirt": 22,
  "Armor": 23,
  "Ninja Garb": 24,
  "Service": 25,
  "Hawaiian": 26,
  "Rave Hoodie": 27,
  "School": 28,
  "Cyber Samurai": 29,
  "Cyber Suit": 30,
  "Neo Armor": 31,
  "Zombie Robot": 32,
  "Onesie": 33,
  "Power Suit": 34,
  "Demon Suit": 35,
  "Mecha Ninja": 36,
  "Giant Mech": 37,
  "Ape": 38,
  "Space Suit": 39,
  "Akira Jacket": 40,
  "Angel with Wings": [41, '41-0'],
  "Translucent": [42, '42-1'],
  "No Skin": 43,
  "Devil 1": 35,
  "Devil 2": 35,
  "Devil 3": 35,
  "Angel 1": [41, '41-0'],
  "Angel 2": [41, '41-0'],
  "Angel 3": [41, '41-0'],
  "Dark Space Wizard": 50,
  "Tri-Angle Hero": 51,
  "Chief Master": 52,
  "Doom Man": 53,
  "Ichigo": 54,
  "Metraidish": 55,
  "Super Italian Guy": 56,
}

const maleWeapons = {
  "None" : null,
  "Pocket Knife": 0,
  "Pea Shooter": 1,
  "Rolled Up Newspaper": [2 ,'2-0'],
  "Brass Knuckles": 3,
  "Taser": 4,
  "Sword": [5, '5-0'],
  "Pistol": 6,
  "Rifle": 7,
  "Shield": 8,
  "Cyber Katana": [9, '9-0'],
  "Plasma Rifle": 10,
  "50 Cal Magnum": 11,
  "Missile Launcher": 12,
  "Minigun": 13,
  "Super Shotgun": 14,
  "Charge Blade": [15, '15-0'],
  "Light Saber": [16, '16-0'],
  "Golden Sock": 17,
  "Gravity Gun": 18,
  "Golden Hilt Red Light Saber": [19, '19-0'],
  "Sword of Masters": [20, '20-0'],
  "Energy Sword": 21,
  "BFG 9000": 22,
  "Buster Sword": [23, '23-0'],
  "Metraid Hand Blaster": 24,
  "Blades of Chaos": [25, '25-0'],
}

const wpnTypeToHand = {
  '0': 'melee',
  '1': 'gun',
  '2': 'melee',
  '3': 'fist',
  '4': 'gun',
  '5': 'melee',
  '6': 'gun',
  '7': 'gun',
  '8': 'melee',
  '9': 'melee',
  '10': 'gun',
  '11': 'gun',
  '12': 'gun',
  '13': 'gun',
  '14': 'gun',
  '15': 'melee',
  '16': 'melee',
  '17': 'melee',
  '18': 'gun',
  '19': 'melee',
  '20': 'melee',
  '21': 'fist',
  '22': 'gun',
  '23': 'melee',
  '24': 'fist',
  '25': 'melee',
}


const assets = {
  male: {
    hands: wpnTypeToHand,
    backgrounds,
    helms: maleHelmets,
    clothing: maleClothing,
    weapons: maleWeapons,
    bodies: {
      Human: 0,
      Android: 1,
      Mutant: 2,
      Albino: 3,
      Ape: 4,
      Ghost: 5,
      Demon: 6,
      Aeon: 7,
      Phantom: 8,
    }
  },
  female: {

  },
}


export default assets;
